# Generated by Django 5.0.2 on 2024-02-22 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_login_delete_mymodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='Users',
        ),
    ]
